spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: aggregationdb
      username: aggregationlabuser
      password: bk2rFn*d

# Enable Logging mongo queries
logging:
  level:
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG