spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: menudb
      username: admin
      password: admin

# Enable Logging mongo queries
logging:
  level:
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG